-- ==========================================================================
-- CyberHunt Teams Seed: 76 Event Participants + 10 Demo Accounts
-- Generated for HWIJDCOEM CyberHunt
-- ==========================================================================

INSERT INTO teams (team_id, team_name, leader_email, score, current_level, ai_strikes, global_hints_used, fragments, is_disqualified, level_hints)
VALUES
  ('HWIJDCOEM001', 'Saniya Sanjay Pathe', 'pathess@jdcoem.ac.in', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM002', 'Vrushali Khobragade', 'vrushalikhobragade45@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM003', 'Revati Deulkar', 'deulkarrs@jdcoem.ac.in', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM004', 'Swarakshi Ambade', 'ambadesg@jdcoem.ac.in', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM005', 'Nishant kose', 'nishantkose@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM006', 'Shruti Mangal Parate', 'shrutiparate3@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM007', 'Mahesh Rokde', 'rokdemk@jdcoem.ac.in', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM008', 'Sakshi Khandare', 'khandaresp@jdcoem.ac.in', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM009', 'Tanvi Ghodeswar', 'tanvighodeswar31@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM010', 'Arnav more', 'arnavrajendramore@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM011', 'Nihar Shravan Watekar', 'watekarshravan@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM012', 'Vedika Nandurkar', 'nandurkarvs@jdcoem.ac.in', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM013', 'Prajakta Dinesh Thool', 'thoolpd@jdcoem.ac.in', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM014', 'RUCHIKA RAVEKAR', 'ruchikaravekar2006@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM015', 'Manasvi Raut', 'rautmn@jdcoem.ac.in', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM016', 'Ved Naikele', 'vednaikele@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM017', 'Bhargavi Ninave', 'bhargavininave@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM018', 'Ruhina fatma', 'zoya04128@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM019', 'Harshal Dafe', 'harshaldafe27@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM020', 'Apurva Khadse', 'apurvarkhadse@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM021', 'Ishwari shete', 'ishhshete@email.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM022', 'BADAL Khobragade', 'khobragademotilal@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM023', 'Kamna vinod helonde', 'kamnahelonde30@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM024', 'Nitish Maidanwar', 'nitishmaidanwar@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM025', 'Vaibhav Parkhi', 'vaibhavparkhi15@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM026', 'Sohan Vinod Akotkar', 'sohanakotkar6@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM027', 'Rohan Thaokar', 'rohanthaokar444@jdcoem.ac.in', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM028', 'Rohan Thaokar', 'rohanthaokar444@jdcoem.ac.in', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM029', 'Tejas Kailash Sahare', 'tejassahare71@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM030', 'Muktai Rakshe', 'muktairakshe78@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM031', 'Leena Kinkar', 'leenakinkar39@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM032', 'Sanisa Bhele', 'sanisabhele18@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM033', 'Rizwan Sheikh', 'rizwansheikh0000001@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM034', 'Sampada Shahare', 'daminishahare7@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM035', 'Alfiya Pathan', 'javedkhanpa@jdcoem.ac.in', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM036', 'Roshani Mukeshwar Tembhare', 'tembhareroshni70@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM037', 'Shrushti Hemant wanere', 'shrushtiwanere@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM038', 'Suhani Gajbhiye', 'suhanigajbhiye0@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM039', 'Siddhi Thawkar', 'siddhithawkar2007@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM040', 'Khushal Raju Burde', 'burdekhushal517@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM041', 'Parineeta Charbhe', 'parineetacharbhe68@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM042', 'Minal Bhise', 'bhiseminal1@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM043', 'Pranay Turakane', 'pranayturakane743@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM044', 'Mayank Thool', 'bt250616ds@jdcoem.ac.in', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM045', 'Riya Lanjekar', 'riyalanjekar72@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM046', 'Bhargavi pramod kotte', 'bhumikotte1@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM047', 'Samruddhi Dambhare', 'dambharesamruddhi7@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM048', 'Tanushree Jaulkar', 'tanushreejaulkar9581@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM049', 'SANJIVANI DUPARE', 'sanjivanidupare99@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM050', 'Suhani Nistane', 'suhaninistane1@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM051', 'Divyani Kawde', 'kawdedivyani@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM052', 'Twinkle armarkar', 'twinklearmarkar@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM053', 'Tanushree Yadav', 'tanushreeyadav275@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM054', 'Aditi katare', 'katareaditi077@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM055', 'Aditi Vijay Nandankar', 'aditinandankar2@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM056', 'Gauri Barapatre', 'gauribarapatre07@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM057', 'Maithili Pramod Koche', 'kochemp@jdcoem.ac.in', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM058', 'Tanushree bhalerao', 'tanushreebhalerao94@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM059', 'Gauri Bode', 'gauribode@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM060', 'Nishant Asutkar', 'asutkarnishant@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM061', 'Shrijit Suresh Adhau', 'shrijitadhau@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM062', 'Sakshi anil pandey', 'sakshipandey8221@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM063', 'Sanjana barve', 'sanjanabarve25@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM064', 'Harsh Juzhare', 'harshjuzhare@jdcoem.ac.in', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM065', 'Kunal Shende', 'kunalshende115@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM066', 'VAISHNAVI SUNIL ASARE', 'asarevs@jdcoem.ac.in', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM067', 'Kavita Subhash Paswan', 'kavitapaswan518@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM068', 'Anushka Munne', 'anushkamunne286@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM069', 'Ritesh Prakash Chopade', 'riteshchopade393@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM070', 'Khomit Mandhare', 'khomitytmandhare@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM071', 'PRATIK TEMBHARE', 'pratiktembhare84@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM072', 'Aditya wadnere', 'wadnere004@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM073', 'Khushi Kewat', 'khushikewat949@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM074', 'Arsalan khan wajed khan', 'arsalankhan2005k@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM075', 'Janhvi Nimbalkar', 'janvinimbalkar21@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('HWIJDCOEM076', 'Ekta uprade Uprade', 'ektaupradeuprade@gmail.com', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('DEMO-KEY-001', 'Demo Agent Alpha', 'demo01@cyberhunt.io', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('DEMO-KEY-002', 'Demo Agent Beta', 'demo02@cyberhunt.io', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('DEMO-KEY-003', 'Demo Agent Gamma', 'demo03@cyberhunt.io', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('DEMO-KEY-004', 'Demo Agent Delta', 'demo04@cyberhunt.io', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('DEMO-KEY-005', 'Demo Agent Epsilon', 'demo05@cyberhunt.io', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('DEMO-KEY-006', 'Demo Agent Zeta', 'demo06@cyberhunt.io', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('DEMO-KEY-007', 'Demo Agent Eta', 'demo07@cyberhunt.io', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('DEMO-KEY-008', 'Demo Agent Theta', 'demo08@cyberhunt.io', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('DEMO-KEY-009', 'Demo Agent Iota', 'demo09@cyberhunt.io', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb),
  ('DEMO-KEY-010', 'Demo Agent Kappa', 'demo10@cyberhunt.io', 0, 1, 0, 0, ARRAY['','','','','','','','',''], FALSE, '{}'::jsonb)
ON CONFLICT (team_id) DO UPDATE SET
  team_name = EXCLUDED.team_name,
  leader_email = EXCLUDED.leader_email;
